spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: keycloak_oidc
              uri: ${KEYCLOAK_UMA_SERVER_URL:http://keycloak:8080}
              predicates:
                - Path=/realms/**
            - id: admin_management
              uri: http://admin-management:8080
              predicates:
                - Path=/v1/admin_management/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - TokenRelay
            - id: inventory_management
              uri: http://inventory-management:8080
              predicates:
                - Path=/v1/inventory_management/**
                - Method=GET,POST,PUT,DELETE
              filters:
                - TokenRelay
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL:http://localhost:8090}/realms/${KEYCLOAK_UMA_REALM:api-gateway-realm}
          jwk-set-uri: ${KEYCLOAK_UMA_SERVER_URL:http://keycloak:8080}/realms/${KEYCLOAK_UMA_REALM:api-gateway-realm}/protocol/openid-connect/certs

keycloak:
  uma:
    server-url: ${KEYCLOAK_UMA_SERVER_URL:http://keycloak:8080}
    realm: ${KEYCLOAK_UMA_REALM:api-gateway-realm}
    audience: ${KEYCLOAK_UMA_AUDIENCE:api-gateway-client}
    cache-ttl-seconds: 30

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

server:
  port: 8090
